apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-ingress
spec:
  rules:
{{- range .Values.ingress.hosts }}
# Ex: dev.frontend.minikube.local
  - host: {{ $.Release.Name }}.{{ .host.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
            serviceName: {{ $.Release.Name}}-{{ .host.chart }}
            servicePort: 80
{{- end }}
