# Since DB uname/pswd is common to the entire chart, we can override the backend values with admin values in the umbrella chart
# IMP retain the same hierarchy as backend.values.yaml
# common practice when re-using existing charts from Helm repository
backend:
  secret:
    mongodb_uri:
      username: admin
      password: admin
  ingress:
    # override backend settings 
    enabled: false
frontend:
  ingress:
     # override frontend settings
    enabled: false

ingress:
  hosts:
    - host:
        domain: frontend.minikube.local
        chart: frontend
    - host:
        domain: backend.minikube.local
        chart: backend
